PROJECT = wterm
PROJECT_DESCRIPTION = ssh web terminal
PROJECT_VERSION = 0.1.0

DEPS = cowboy lager getopt
dep_cowboy_commit = 2.9.0
dep_getopt_commit = v1.0.2

DEP_PLUGINST = cowboy

include erlang.mk
